shop/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.card_add,name='cart_add'),
    path('minus/<int:product_id>/',views.card_minus,name='cart_minus'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('all_remove/',views.all_remove,name='all_remove')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_views, name='profile'),
    path('account-details/', views.account_details, name='account_details'),
    path('edit-account-details/', views.edit_account_details, name='edit_account_details'),
    path('update-account-details/', views.update_account_details, name='update_account_details'),
    path('logout/', views.logout_view, name='logout'),
]

shop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, \
    BaseUserManager
from django.utils.html import strip_tags


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('The email field must be set.')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    
    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, max_length=66)
    first_name = models.CharField(max_length=66)
    last_name = models.CharField(max_length=66)
    address1 = models.CharField(max_length=128, blank=True, null=True)
    address2 = models.CharField(max_length=128, blank=True, null=True)
    city = models.CharField(max_length=128, blank=True, null=True)
    country = models.CharField(max_length=128, blank=True, null=True)
    province = models.CharField(max_length=128, blank=True, null=True)
    postal_code = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    marketing_consent1 = models.BooleanField(default=False)
    marketing_consent2 = models.BooleanField(default=False)

    username = models.CharField(max_length=150, unique=True, null=True, blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']


    def __str__(self):
        return self.email
    

    def clean(self):
        for field in ['address1', 'address2', 'city', 'country', 'province',
                          'postal_code', 'phone']:
            value = getattr(self, field)
            if value:
                setattr(self, field, strip_tags(value))

shop/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, authenticate
from django.utils.html import strip_tags
from django.core.validators import RegexValidator


User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        max_length=66,
        widget=forms.EmailInput(attrs={'class': 'input-register form-control', 'placeholder': 'Email'})
    )
    first_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Имя'})
    )
    last_name = forms.CharField(
        required=False,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your last name'}
                               ),
                               
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'input-register form-control', 'placeholder': 'Пароль'})
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'input-register form-control', 'placeholder': 'Повторите пароль'})
    )
    marketing_consent1 = forms.BooleanField(
        required=True,
        label="Соглашаюсь получать новости и специальные предложения",
        widget=forms.CheckboxInput(attrs={'class': 'checkbox-input-register'})
    )
    marketing_consent2 = forms.BooleanField(
        required=False,
        label="I agree to receive personalized commercial communications.",
        widget=forms.CheckboxInput(attrs={'class': 'checkbox-input-register'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',
                  'marketing_consent1', 'marketing_consent2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Эта почта уже используется.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = None
        user.marketing_consent1 = self.cleaned_data['marketing_consent1']
        user.marketing_consent2 = self.cleaned_data['marketing_consent2']
        if commit:
            user.save()
        return user
    

class CustomUserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Email',
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'input-register form-control', 'placeholder': 'Email'})
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'input-register form-control', 'placeholder': 'Пароль'})
    )

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(self.request, username=email, password=password)  # Используйте username вместо email
            if self.user_cache is None:
                raise forms.ValidationError('Неверно указана почта или пароль.')
            elif not self.user_cache.is_active:
                raise forms.ValidationError('Этот аккаунт неактивен.')
        return self.cleaned_data
    

class CustomUserUpdateForm(forms.ModelForm):
    phone = forms.CharField(
        required=False,
        validators=[RegexValidator(r'^\+?1?\d{9,15}$', "Введите правильный номер телефона.")],
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Номер телефона'})
    )
    first_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Имя'})
    )
    last_name = forms.CharField(
        required=False,
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'input-register form-control', 'placeholder': 'Your last name'})
    )
    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(attrs={'class': 'input-register form-control', 'placeholder': 'Email'})
    )


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'address1', 'address2',
                  'city', 'country', 'province', 'postal_code', 'phone')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'input-register form-control', 
                                             'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                'placeholder': 'Your last name'}),
            'address1': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Адрес'}),
            'address2': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Address line 2'}),
            'city': forms.TextInput(attrs={'class': 'input-register form-control', 
                                           'placeholder': 'Your city'}),
            'country': forms.TextInput(attrs={'class': 'input-register form-control', 
                                              'placeholder': 'Your country'}),
            'province': forms.TextInput(attrs={'class': 'input-register form-control', 
                                               'placeholder': 'Your province'}),
            'postal_code': forms.TextInput(attrs={'class': 'input-register form-control', 
                                                  'placeholder': 'Your postal code'}),
        }

    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('Эта почта уже используется.')
        return email
    

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('email'):
            cleaned_data['email'] = self.instance.email

        for field in ['address1', 'address2', 'city', 'country', 'province',
                        'postal_code', 'phone']:
            if cleaned_data.get(field):
                cleaned_data[field] = strip_tags(cleaned_data[field])

        return cleaned_data

shop/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserLoginForm, CustomUserUpdateForm
from .models import CustomUser


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:profile')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('users:profile')
    else:
        form = CustomUserLoginForm()
    return render(request, 'login.html', {'form': form})


@login_required
def profile_views(request):
    return render(request, 'profile.html', {'user': request.user})


@login_required
def account_details(request):
    user = CustomUser.objects.get(id=request.user.id)
    return render(request, 'account_details.html', {'user': user})


@login_required
def edit_account_details(request):
    form = CustomUserUpdateForm(instance=request.user)
    return render(request, 'edit_account_details.html', {'user': request.user, 'form': form})


@login_required
def update_account_details(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.clean()
            user.save()
            return render(request, 'profile.html', {'user': user})
        else:
            return render(request, 'edit_account_details.html', {'user': request.user, 'form': form})
    # return render(request, 'users/partials/account_details.html', {'user': request.user})


def logout_view(request):
    logout(request)
    return redirect('users:register')

shop/users/templates/edit_account_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit account{% endblock %}
{% block link %}<link rel="stylesheet" href="{% static "css/edit_account_details.css" %}">{% endblock link %}
{% block content %}
<div class="wrapper"> 
    <div class="address-box">
       
        <form action="{% url 'users:update_account_details' %}" method="post">
            {% csrf_token %}
            <h1 class="text1 text_40px black weight_700">Изменение информации</h1>
           
               
                   
                        
                <label for="{{ form.first_name.id_for_label }}" class='text3 text_24px black'>Имя</label>
            {{ form.first_name }}
            {% if form.first_name.errors %}
                <div class="error">{{ form.first_name.errors }}</div>
            {% endif %}
        
            <label for="{{ form.address1.id_for_label }}" class='text4 text_24px black'>Адрес</label>
            {{ form.address1 }}
            {% if form.address1.errors %}
                <div class="error">{{ form.address1.errors }}</div>
            {% endif %}
        
            <label for="{{ form.phone.id_for_label }}" class='text5 text_24px black'>Телефон</label>
            {{ form.phone }}
            {% if form.phone.errors %}
                <div class="error">{{ form.phone.errors }}</div>
            {% endif %}
       
                <button type="submit" class="button link text_24px black">Обновить</button>
                <a href="{% url "users:profile" %}" class="link text_16px black">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

shop/users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Log In{% endblock %}
{% block link %}<link rel="stylesheet" href="{% static "css/login.css" %}">{% endblock link %}
{% block content %}
<div class="wrapper"> 
    <h1 class='text1 text_40px black weight_700'>Вход</h1>
    <form method="post" class="reg-form">
        {% csrf_token %}
       
            <label for="{{ form.username.id_for_label }}" class='text2 text_24px black'>Email</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error">{{ form.username.errors }}</div>
            {% endif %}
       
            <label for="{{ form.password.id_for_label }}" class='text3 text_24px black'>Пароль</label>
            {{ form.password }}
            {% if form.password.errors %}
                <div class="error">{{ form.password.errors }}</div>
            {% endif %}
       
        <button type="submit" class='button text_24px black'>Войти</button>
        <a href="{% url 'users:register' %}" class="link text_16px black">Нет аккаунта? Зарегистрироваться.</a>
    </form>
 </div>
{% endblock %}

shop/users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create Account{% endblock %}
{% block link %}<link rel="stylesheet" href="{% static "css/register.css" %}">{% endblock link %}
{% block content %}
<div class="wrapper"> 
    <h1  class='text1 text_40px black weight_700'>Регистрация</h1>
    <form method="post" class="reg-form">
        {% csrf_token %}
        
            <label for="{{ form.first_name.id_for_label }} " class='label text2 text_24px black'>Имя</label>
            {{ form.first_name }}
            {% if form.first_name.errors %}
                <div class="error">{{ form.first_name.errors }}</div>
            {% endif %}
        
        
           
        
            <label for="{{ form.email.id_for_label }}" class='text3 text_24px black'>Email</label>
            {{ form.email }}
            {% if form.email.errors %}
                <div class="error">{{ form.email.errors }}</div>
            {% endif %}
        
            <label for="{{ form.password1.id_for_label }}" class='text4 text_24px black'>Пароль</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="error">{{ form.password1.errors }}</div>
            {% endif %}
        
            <label for="{{ form.password2.id_for_label }}" class='text5 text_24px black'>Подтвердите пароль</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="error">{{ form.password2.errors }}</div>
            {% endif %}
       
            
            <label for="{{ form.marketing_consent1.id_for_label }}" class='text6 text_12px black'>
                {{ form.marketing_consent1 }}
                Я принимаю пользовательское соглашение.
            </label>
            {% if form.marketing_consent1.errors %}
                <div class="error">{{ form.marketing_consent1.errors }}</div>
            {% endif %}
        
        
       
        <button type="submit" class="button text_24px black">Зарегистрироваться</button>
        <a href="{% url 'users:login' %}" class="link text_16px black">Уже зарегистрированы? Войти.</a>
    </form>
 </div>
{% endblock %}