shop/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.card_add,name='cart_add'),
    path('minus/<int:product_id>/',views.card_minus,name='cart_minus'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('all_remove/',views.all_remove,name='all_remove')
]

shop/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('/search', views.product_search, name='product_search'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('users.urls', namespace='users')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_list_by_category", args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    description = models.TextField(blank=True)
    expiration_date = models.TextField(blank=True)
    weight = models.TextField(blank=True)
    producer = models.TextField(blank=True)
    country_of_production = models.TextField(blank=True)
    composition = models.TextField(blank=True)
    storage_conditions = models.TextField(blank=True)
    brand = models.TextField(blank=True)
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_detail", args=[self.id, self.slug])

shop/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    category = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request,
        'index.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'cart_product_form': cart_product_form,
        },
    )


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    related_products = Product.objects.filter(category=product.category, available=True).exclude(id=product.id)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'detail.html',
        {'product': product, 'related_products': related_products[:15], 'cart_product_form': cart_product_form},
    )


def product_search(request):
    if request.method == "POST":
        cart_product_form = CartAddProductForm()
        searched = request.POST['searched']
        searched_products = Product.objects.filter(name__istartswith=searched)
        return render(
            request,
            'index.html',
            {'searched': searched, 'products': searched_products, "cart_product_form": cart_product_form},
        )
    return render(request, 'index.html')

shop/main/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{product.name}}
{% endblock title %}

{% block link %}  <link rel="stylesheet" href="{% static "css/detail.css" %}">{% endblock link %}
        

{% block content %}
     <div class="wrapper"> 
        <div class="block">
            <div class="part1">
                <div>
                    <h2 class="item-name text_40px black weight_700">{{product.name}}</h2>
                    <p class="item-quantity text_14px grey">{{product.weight}}</p>
                    <p class="item-price text_24px black">{{product.price}} {% if  product.weight%}₽/шт{% else %}₽/кг{% endif %}</p>
                    
                </div>
                <form action="{% url "cart:cart_add" product.id %}" method="post" class="form5">
                    {{ cart_product_form }}
                        {% csrf_token %}
                    <button class="item-button">
                            {% comment %} <img src="{% static "img/cart2.svg" %}" alt=""> {% endcomment %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="18px" height="18px"viewBox="0 0 24 24"><symbol xmlns="http://www.w3.org/2000/svg" id="a" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M7.18 13.534 6.167 7.966h12.216l-2.088 5.568zM4.295 2c.598 0 1.108.432 1.206 1.021l.455 2.729h13.493a1.477 1.477 0 0 1 1.383 1.996L18.19 14.79a1.48 1.48 0 0 1-1.383.959H5.427a.116.116 0 0 1-.114-.095L3.093 3.44C2.956 2.69 3.533 2 4.295 2M15.96 22a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75m-8.75 0a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75" clip-rule="evenodd"/></symbol><use href="#a"/></svg>
                            
                            <span class="text_16px white weight_700">В корзину</span>
                    </button>
                </form>
            </div>
            <div class='part2'>
                <a href="{{product.get_absolute_url}}">
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </a>
            </div>
            <div>
                <h3 class='black text_24px '>Описание</h3>
                <p class='description black text_16px'>{{product.description}}</p>
            </div>
        </div>

        <div class="block2">
            {% if  product.expiration_date%}
            <div class="w350">
                <p class="text_16px black weight_700">Годен</p>
                <p class="text_16px black">{{product.expiration_date}}</p>
            </div>
            {% endif %}
            {% if  product.producer%}
            <div class="w350">
                <p class="text_16px black weight_700">Изготовитель</p>
                <p class="text_16px black">{{product.producer}}</p>
            </div>
            {% endif %}
            {% if  product.country_of_production%}
            <div class="w350"> 
                <p class="text_16px black weight_700">Страна производства</p>
                <p class="text_16px black">{{product.country_of_production}}</p>
            </div>
            {% endif %}
            {% if product.composition %}
            <div id="grid-position">
                <p class="text_16px black weight_700">Состав</p>
                <p class="text_16px black">{{product.composition}}</p>
            </div>
            {% endif %}
            {% if product.storage_conditions %}
            <div class="w350">
                <p class="text_16px black weight_700">Условия хранения</p>
                <p class="text_16px black">{{product.storage_conditions}}</p>
            </div>
            {% endif %}
           
        </div>

        <div class="block3">
            <p class="text_40px black weight_600 text15">Рекомендуем к покупке</p>
             <ul class="list">
            {% for product in  related_products%}
            <li class="item">
                <a href="{{product.get_absolute_url}}" class='item-img-link'>
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </a>
                <div>
                    <div>
                    <a href="{{product.get_absolute_url}}" >
                        <h5 class="item-name text_16px black">{{product.name}}</h5>
                    </a>
                    <p class="item-quantity text_14px grey">{{product.weight}}</p>
                    <p class="item-price text_16px black">{{product.price}} {% if  product.weight%}₽/шт{% else %}₽/кг{% endif %}</p>
                    </div>
                    <form action="{% url "cart:cart_add" product.id %}" method="post" class="form1">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <button class="item-button" type="submit">
                            {% comment %} <img src="{% static "img/cart2.svg" %}" alt=""> {% endcomment %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="18px" height="18px"viewBox="0 0 24 24"><symbol xmlns="http://www.w3.org/2000/svg" id="a" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M7.18 13.534 6.167 7.966h12.216l-2.088 5.568zM4.295 2c.598 0 1.108.432 1.206 1.021l.455 2.729h13.493a1.477 1.477 0 0 1 1.383 1.996L18.19 14.79a1.48 1.48 0 0 1-1.383.959H5.427a.116.116 0 0 1-.114-.095L3.093 3.44C2.956 2.69 3.533 2 4.295 2M15.96 22a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75m-8.75 0a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75" clip-rule="evenodd"/></symbol><use href="#a"/></svg>
                            
                            <span class="text_16px white">В корзину</span>
                        </button>
                    </form>
                </div>
            </li>
            {% endfor %}
        
        </ul>
        </div>
    </div>
{% endblock content %}

shop/main/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{category.name}}{% else %}Товары{% endif %}
{% endblock title %}

{% block link %}<link rel="stylesheet" href="{% static "css/index.css" %}">{% endblock link %}

{% block content %}
    <div class="wrapper"> 
        
        <ul class="list">
            {% for product in  products%}
            <li class="item">
                <a href="{{product.get_absolute_url}}" class='item-img-link'>
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </a>
                <div>
                    <div>
                    <a href="{{product.get_absolute_url}}" >
                        <h5 class="item-name text_16px black weight_500">{{product.name}}</h5>
                    </a>
                    <p class="item-category text_14px black">{{product.category}}</p>
                    {% if product.weight %}
                        <p class="item-quantity text_14px grey">{{product.weight}}</p>
                    {% endif %}
                    <p class="item-price text_16px black">
                        {{product.price}} {% if  product.weight%}₽/шт{% else %}₽/кг{% endif %}
                    </p>
                    </div>
                    <form action="{% url "cart:cart_add" product.id %}" method="POST" class="form1">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <button class="item-button" type="submit">
                            {% comment %} <img src="{% static "img/cart2.svg" %}" alt=""> {% endcomment %}
                            <svg xmlns="http://www.w3.org/2000/svg" fill="white" width="18px" height="18px"viewBox="0 0 24 24"><symbol xmlns="http://www.w3.org/2000/svg" id="a" viewBox="0 0 24 24"><path fill-rule="evenodd" d="M7.18 13.534 6.167 7.966h12.216l-2.088 5.568zM4.295 2c.598 0 1.108.432 1.206 1.021l.455 2.729h13.493a1.477 1.477 0 0 1 1.383 1.996L18.19 14.79a1.48 1.48 0 0 1-1.383.959H5.427a.116.116 0 0 1-.114-.095L3.093 3.44C2.956 2.69 3.533 2 4.295 2M15.96 22a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75m-8.75 0a1.875 1.875 0 1 0 0-3.75 1.875 1.875 0 0 0 0 3.75" clip-rule="evenodd"/></symbol><use href="#a"/></svg>
                            
                            <span class="text_16px white">В корзину</span>
                        </button>
                    </form>
                </div>
            </li>
            {% endfor %}
        
        </ul>
      </div>
{% endblock content %}

shop/main/templates/product_search.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{category.name}}{% else %}Товары{% endif %}
{% endblock title %}

{% block link %}<link rel="stylesheet" href="{% static "css/product_search.css" %}">{% endblock link %}

{% block content %}


{% endblock content %}